{% set version = "1.3-8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rworldmap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rworldmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rworldmap/rworldmap_{{ version }}.tar.gz
  sha256: a60ec649f70a7537fdbe65fed58d2c48a1b191cd944681eef2944279a8dcea00

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fields
    - r-maptools
    - r-sp
  run:
    - r-base
    - r-fields
    - r-maptools
    - r-sp

test:
  commands:
    - $R -e "library('rworldmap')"           # [not win]
    - "\"%R%\" -e \"library('rworldmap')\""  # [win]

about:
  home: https://github.com/AndySouth/rworldmap/, https://groups.google.com/forum/#!forum/rworldmap, http://andysouth.co.uk/
  license: GPL-2.0-or-later
  summary: Enables mapping of country level and gridded user datasets.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - colineroyaux

# Package: rworldmap
# Type: Package
# Title: Mapping Global Data
# Version: 1.3-6
# Date: 2016-02-03
# Author: Andy South
# Maintainer: Andy South <southandy@gmail.com>
# Description: Enables mapping of country level and gridded user datasets.
# License: GPL (>= 2)
# Depends: R (>= 2.10.0), sp
# Imports: maptools, fields, methods
# Suggests: rgdal, rworldxtra, RColorBrewer, classInt
# LazyData: true
# URL: https://github.com/AndySouth/rworldmap/, https://groups.google.com/forum/#!forum/rworldmap, http://andysouth.co.uk/
# BugReports: https://github.com/AndySouth/rworldmap/issues
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-02-03 10:04:28 UTC; andy
# Repository: CRAN
# Date/Publication: 2016-02-03 12:26:35
